server:
  port: 8002

spring:
  application:
    name: payments-service
  data:
    mongodb:
      uri: "mongodb+srv://mark:mazare123@greencluster.rewht.mongodb.net/course13Db?retryWrites=true&w=majority"
  rabbitmq:
    host: cow.rmq2.cloudamqp.com
    username: divoayef
    password: GBvJg_Pkw166v1Uu3ri8WZRYXKp1vvZC
    virtual-host: divoayef

invoice-service-host: "http://localhost:8001"
